name: sparsecca
channels:
  - conda-forge
dependencies:
  - python<=3.9
  - jupyterlab
  - ipykernel
  # sparsecca dependencies
  - rpy2
  - pytest
  - pandas
  - numpy
  - statsmodels
  - pip
  - pip:
    - git+https://github.com/theislab/sparsecca.git
